TerrainBuilder/Areas/Meetings/Controllers/MeetingStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TerrainBuilder.Data;

namespace TerrainBuilder.Areas.Meetings.Controllers
{
    [Area("Meetings")]
  //  [Route("{controller=Home}/{action=Index}/{id?}")]
    [Authorize(Roles = "Administrator" )]
    public class MeetingStatusController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MeetingStatusController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MeetingStatus
        public async Task<IActionResult> Index()
        {
              return View(await _context.MeetingStatuses.ToListAsync());
        }

        // GET: MeetingStatus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.MeetingStatuses == null)
            {
                return NotFound();
            }

            var meetingStatus = await _context.MeetingStatuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meetingStatus == null)
            {
                return NotFound();
            }

            return View(meetingStatus);
        }

        // GET: MeetingStatus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MeetingStatus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] MeetingStatus meetingStatus)
        {
            if (ModelState.IsValid)
            {
                _context.Add(meetingStatus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(meetingStatus);
        }

        // GET: MeetingStatus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MeetingStatuses == null)
            {
                return NotFound();
            }

            var meetingStatus = await _context.MeetingStatuses.FindAsync(id);
            if (meetingStatus == null)
            {
                return NotFound();
            }
            return View(meetingStatus);
        }

        // POST: MeetingStatus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] MeetingStatus meetingStatus)
        {
            if (id != meetingStatus.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(meetingStatus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeetingStatusExists(meetingStatus.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(meetingStatus);
        }

        // GET: MeetingStatus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.MeetingStatuses == null)
            {
                return NotFound();
            }

            var meetingStatus = await _context.MeetingStatuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meetingStatus == null)
            {
                return NotFound();
            }

            return View(meetingStatus);
        }

        // POST: MeetingStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.MeetingStatuses == null)
            {
                return Problem("Entity set 'ApplicationDbContext.MeetingStatus'  is null.");
            }
            var meetingStatus = await _context.MeetingStatuses.FindAsync(id);
            if (meetingStatus != null)
            {
                _context.MeetingStatuses.Remove(meetingStatus);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MeetingStatusExists(int id)
        {
          return _context.MeetingStatuses.Any(e => e.Id == id);
        }
    }
}

TerrainBuilder/Controllers/MeetingStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TerrainBuilder.Data;

namespace TerrainBuilder.Controllers
{
    public class MeetingStatusController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MeetingStatusController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MeetingStatus
        public async Task<IActionResult> Index()
        {
              return View(await _context.MeetingStatuses.ToListAsync());
        }

        // GET: MeetingStatus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.MeetingStatuses == null)
            {
                return NotFound();
            }

            var meetingStatus = await _context.MeetingStatuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meetingStatus == null)
            {
                return NotFound();
            }

            return View(meetingStatus);
        }

        // GET: MeetingStatus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MeetingStatus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] MeetingStatus meetingStatus)
        {
            if (ModelState.IsValid)
            {
                _context.Add(meetingStatus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(meetingStatus);
        }

        // GET: MeetingStatus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MeetingStatuses == null)
            {
                return NotFound();
            }

            var meetingStatus = await _context.MeetingStatuses.FindAsync(id);
            if (meetingStatus == null)
            {
                return NotFound();
            }
            return View(meetingStatus);
        }

        // POST: MeetingStatus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] MeetingStatus meetingStatus)
        {
            if (id != meetingStatus.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(meetingStatus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeetingStatusExists(meetingStatus.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(meetingStatus);
        }

        // GET: MeetingStatus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.MeetingStatuses == null)
            {
                return NotFound();
            }

            var meetingStatus = await _context.MeetingStatuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meetingStatus == null)
            {
                return NotFound();
            }

            return View(meetingStatus);
        }

        // POST: MeetingStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.MeetingStatuses == null)
            {
                return Problem("Entity set 'ApplicationDbContext.MeetingStatus'  is null.");
            }
            var meetingStatus = await _context.MeetingStatuses.FindAsync(id);
            if (meetingStatus != null)
            {
                _context.MeetingStatuses.Remove(meetingStatus);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MeetingStatusExists(int id)
        {
          return _context.MeetingStatuses.Any(e => e.Id == id);
        }
    }
}

TerrainBuilder/Areas/Meetings/Views/MeetingStatus/Create.cshtml
@model TerrainBuilder.Data.MeetingStatus

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MeetingStatus</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-area="Meetings" asp-controller="MeetingStatus" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TerrainBuilder/Areas/Meetings/Views/MeetingStatus/Delete.cshtml
@model TerrainBuilder.Data.MeetingStatus

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MeetingStatus</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-area="Meetings" asp-controller="MeetingStatus" asp-action="Index">Back to List</a>
    </form>
</div>

TerrainBuilder/Areas/Meetings/Views/MeetingStatus/Details.cshtml
@model TerrainBuilder.Data.MeetingStatus

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MeetingStatus</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-area="Meetings" asp-controller="MeetingStatus" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-area="Meetings" asp-controller="MeetingStatus" asp-action="Index">Back to List</a>
</div>

TerrainBuilder/Areas/Meetings/Views/MeetingStatus/Edit.cshtml
@model TerrainBuilder.Data.MeetingStatus

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MeetingStatus</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="Meetings" asp-controller="MeetingStatus" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TerrainBuilder/Areas/Meetings/Views/MeetingStatus/Index.cshtml
@model IEnumerable<TerrainBuilder.Data.MeetingStatus>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-area="Meetings" asp-controller="MeetingStatus" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                 <a asp-area="Meetings" asp-controller="MeetingStatus" asp-action="Edit"asp-route-id="@item.Id">Edit</a>
                <a asp-area="Meetings" asp-controller="MeetingStatus" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-area="Meetings"  asp-controller="MeetingStatus"  asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>