TerrainBuilder/Controllers/MeetingTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TerrainBuilder.Data;

namespace TerrainBuilder.Controllers
{
    public class MeetingTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MeetingTypesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MeetingTypes
        public async Task<IActionResult> Index()
        {
              return View(await _context.MeetingTypes.ToListAsync());
        }

        // GET: MeetingTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.MeetingTypes == null)
            {
                return NotFound();
            }

            var meetingType = await _context.MeetingTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meetingType == null)
            {
                return NotFound();
            }

            return View(meetingType);
        }

        // GET: MeetingTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MeetingTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] MeetingType meetingType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(meetingType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(meetingType);
        }

        // GET: MeetingTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MeetingTypes == null)
            {
                return NotFound();
            }

            var meetingType = await _context.MeetingTypes.FindAsync(id);
            if (meetingType == null)
            {
                return NotFound();
            }
            return View(meetingType);
        }

        // POST: MeetingTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] MeetingType meetingType)
        {
            if (id != meetingType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(meetingType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeetingTypeExists(meetingType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(meetingType);
        }

        // GET: MeetingTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.MeetingTypes == null)
            {
                return NotFound();
            }

            var meetingType = await _context.MeetingTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meetingType == null)
            {
                return NotFound();
            }

            return View(meetingType);
        }

        // POST: MeetingTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.MeetingTypes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.MeetingType'  is null.");
            }
            var meetingType = await _context.MeetingTypes.FindAsync(id);
            if (meetingType != null)
            {
                _context.MeetingTypes.Remove(meetingType);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MeetingTypeExists(int id)
        {
          return _context.MeetingTypes.Any(e => e.Id == id);
        }
    }
}

TerrainBuilder/Controllers/TerrainController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System;
using TerrainBuilder.Contracts;
using TerrainBuilder.Data;
using TerrainBuilder.Models;
using TerrainBuilder.Services;
using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace TerrainBuilder.Controllers
{
    //TODO: Clean Up Controller
    [Authorize]
    public class TerrainController : Controller
    {
        private readonly ITerrainService terrainsv;

        private readonly ApplicationDbContext _context;

        public TerrainController(ITerrainService _terrainsv, ApplicationDbContext context)
        {
            terrainsv = _terrainsv;
            _context = context;
        }

        public async Task<IActionResult> GenerateTerrain(int l, int w, string offX, string offY, int oct, double inf)
        {
            GenerateTerrainViewModel terrain = new GenerateTerrainViewModel();

            string x = terrainsv.ConvertOffset(offX);
            string y = terrainsv.ConvertOffset(offY);

            //150, 150, 83681.452163, 41294.53462, 5, 2
            terrain = await terrainsv.GenerateTerrain(l,w,double.Parse(x),double.Parse(y),oct,inf);
            return View(terrain);
        }

        public async Task<IActionResult> Index()
        {
            var userId = "";
            try
            {
                userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            }
            catch (Exception ex)
            {
                throw new ArgumentException("Invalid user sent");
            }

            ApplicationUser appUser = await _context.Users.Where(m=>m.Id==userId).Include(m=>m.Terrains).FirstOrDefaultAsync();

            List<Terrain> allTerrains = appUser.Terrains.ToList();
            List<TerrainViewModel> tvms = new List<TerrainViewModel>();
            foreach (Terrain terrain in allTerrains) 
            {
                TerrainViewModel tvm = new TerrainViewModel();
                tvm.Id = terrain.Id;
                tvm.OffsetX = terrain.OffsetX;
                tvm.OffsetY = terrain.OffsetY;
                tvm.Width = terrain.Width;
                tvm.Length = terrain.Length;
                tvm.Influence = terrain.Influence;
                tvm.Octaves = terrain.Octaves;
                tvm.Name = terrain.Name;
                tvm.Description = terrain.Description;
                tvms.Add(tvm);
            }
            return View(tvms);
           // return View(await _context.TerrainViewModel.ToListAsync());
        }

        // GET: TerrainViewModels/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Terrains == null)
            {
                return NotFound();
            }

            var terrain = await _context.Terrains
                .FirstOrDefaultAsync(m => m.Id == id);
            if (terrain == null)
            {
                return NotFound();
            }

            TerrainViewModel tvm = new TerrainViewModel();

            tvm.Id = terrain.Id;
            tvm.Name = terrain.Name;
            tvm.Description = terrain.Description;
            tvm.Length = terrain.Length;
            tvm.Width = terrain.Width;
            tvm.OffsetX = terrain.OffsetX;
            tvm.OffsetY = terrain.OffsetY;
            tvm.Octaves = terrain.Octaves;
            tvm.Influence = terrain.Influence;

            return View(tvm);
        }

        // GET: TerrainViewModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TerrainViewModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Length,Width,OffsetX,OffsetY,Octaves,Influence")] TerrainViewModel terrainViewModel)
        {
            var userId = "";
            try
            {
                userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
                
            }
            catch (Exception ex)
            {
                throw new ArgumentException("Invalid user sent");
            }

            string x = HttpContext.Request.Form["OffsetX"].ToString();
            string y = HttpContext.Request.Form["OffsetY"].ToString();

            ModelState.ClearValidationState(nameof(terrainViewModel));
            TerrainViewModel tvm = await terrainsv.CreateTerrain(terrainViewModel, x, y, userId);

            if (tvm.IsDBSaveSuccessful)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(tvm);
        }

        // GET: TerrainViewModels/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Terrains == null)
            {
                return NotFound();
            }

            var terrain = await _context.Terrains.FindAsync(id);
            if (terrain == null)
            {
                return NotFound();
            }

            TerrainViewModel tvm = new TerrainViewModel();
            tvm.Id = terrain.Id;
            tvm.OffsetX = terrain.OffsetX;
            tvm.OffsetY = terrain.OffsetY;
            tvm.Width = terrain.Width;
            tvm.Length = terrain.Length;
            tvm.Influence = terrain.Influence;
            tvm.Octaves = terrain.Octaves;
            tvm.Name = terrain.Name;
            tvm.Description = terrain.Description;

            return View(tvm);
        }

        //// POST: TerrainViewModels/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Description,Length,Width,OffsetX,OffsetY,Octaves,Influence")] TerrainViewModel terrainViewModel)
        {

            if (id != terrainViewModel.Id)
            {
                return NotFound();
            }

            string x = HttpContext.Request.Form["OffsetX"].ToString();
            string y = HttpContext.Request.Form["OffsetY"].ToString();

            TerrainViewModel tvm = await terrainsv.EditTerrain(terrainViewModel, x, y);

            if (tvm.IsDBSaveSuccessful)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(terrainViewModel);
        }

        //// GET: TerrainViewModels/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Terrains == null)
            {
                return NotFound();
            }

            var terrain = await _context.Terrains
                .FirstOrDefaultAsync(m => m.Id == id);
            if (terrain == null)
            {
                return NotFound();
            }

            TerrainViewModel tvm = new TerrainViewModel();

            tvm.Id = terrain.Id;
            tvm.Name = terrain.Name;
            tvm.Description = terrain.Description;
            tvm.Length = terrain.Length;
            tvm.Width = terrain.Width;
            tvm.OffsetX = terrain.OffsetX;
            tvm.OffsetY = terrain.OffsetY;
            tvm.Octaves = terrain.Octaves;
            tvm.Influence = terrain.Influence;

            return View(tvm);
        }

        // POST: TerrainViewModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Terrains == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Terrain'  is null.");
            }
            var terrain = await _context.Terrains.FindAsync(id);
            if (terrain != null)
            {
                terrain.IsDeleted = true;
                _context.Terrains.Update(terrain);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TerrainViewModelExists(Guid id)
        {
            return _context.Terrains.Any(e => e.Id == id);
        }
    }
}

TerrainBuilder/Areas/Meetings/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TerrainBuilder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TerrainBuilder.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TerrainBuilder</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Meetings">Meetings</a>
                        </li>
                        | 
                         @if (this.User?.Identity != null && this.User.Identity.IsAuthenticated )
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Terrain" asp-action="Index">Terrains</a>
                            </li>
                        }
                         @if (this.User?.Identity != null && this.User.Identity.IsAuthenticated && this.User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Meetings" asp-controller="Meetings" asp-action="Index">Meetings Admin</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Meetings" asp-controller="MeetingStatus" asp-action="Index">Meeting Statuses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Meetings" asp-controller="MeetingTypes" asp-action="Index">Meeting Types</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Meetings" asp-controller="Cities" asp-action="Index">Cities</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TerrainBuilder 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>